### PR TITLE
Add Theo for December 26.

### PR DESCRIPTION
**Pull request by ConorMcGee**
I think this is the Theo on this? I'm not certain but guessing based on previous episodes.

### CODE REVIEW

**Comment by ahl** [comment]
It's not. That's a different Theo. Thanks though!

**Comment by ConorMcGee** [comment]
@ahl Oh crap, sorry about that! Could I at least ask that you adhere to [Cunningham's Law](https://meta.wikimedia.org/wiki/Cunningham%27s_Law) in this case, however?

**Comment by ahl** [comment]
Yep! You saying you want a sticker? DM me or email me

**Comment by ConorMcGee** [comment]
Oh that's very kind but I was just wondering who the Theo on this episode was, actually.

**Comment by ahl** [comment]
I'm not sure of his Mastodon handle

**Comment by ConorMcGee** [comment]
Just his name would be great! Sorry I somehow appear to have contrived a sort of comedy sketch out of this. Also it now probably seems like I'm some sort of stalker and not just idly curious.

**Comment by ahl** [comment]
I don't know it; sorry!

**Pull request closed without merging**
