### PR TITLE
November 18th's Shownotes

### PR DESCRIPTION
**Pull request by felix91gr**
TO DO:

- [x] Date
- [x] Title
- [x] Speakers
- [x] Topics
- [ ] Timestamps
- [x] **Special**: list of cool blogs

### CODE REVIEW

**Comment by felix91gr** [comment]
More links I know were part of the convo:

* https://bcantrill.dtrace.org/2013/11/30/the-power-of-a-pronoun/
* https://ahl.dtrace.org/2007/07/05/dtrace-scobleized/

**Comment by felix91gr** [comment]
@scynthiadunlop in https://github.com/scynthiadunlop/WritingForDevelopersBook/tree/main/links, do you have a list of blogs you consider to be, in general, great recommendations overall?

I ask because the list is so long that it might be slightly overwhelming (unless the reader is like me. I will probably open every link because I'm too easily nerd-sniped)

**Comment by scynthiadunlop** [comment]
The 5 covered in Chapter 3 are from ones that trended on HN in the past year... maybe start with those? A handful other cherry picked ones with an eye towards variety...

https://tigerbeetle.com/blog/2023-07-11-we-put-a-distributed-database-in-the-browser
https://engineering.fb.com/2022/10/24/android/android-java-kotlin-migration/
https://www.canva.dev/blog/engineering/ship-shape/
https://fasterthanli.me/articles/i-want-off-mr-golangs-wild-ride
https://bcantrill.dtrace.org/2020/10/11/rust-after-the-honeymoon/
https://redpanda.com/blog/redpanda-vs-kafka-performance-benchmark
https://discord.com/blog/authentication-outage
https://saagarjha.com/blog/2020/05/10/why-we-at-famous-company-switched-to-hyped-technology
https://fasterthanli.me/articles/why-is-my-rust-build-so-slow

**Comment by felix91gr** [comment]
@scynthiadunlop would you recommend me to link to the individual posts directly, or should I link to their general blog page?

(also, damn, Amos' _I want off of mr. golang's wild ride_, such a classic)

**Comment by scynthiadunlop** [comment]
I'd say the specific posts-- though all of those blogs have multiple gems. Whatever is in line with what you're doing for the list as a whole. And yes, Amos is great!

**Comment by felix91gr** [comment]
### Progress report

I've yet to get a response from Will Snow regarding their socials.

The topical links are in there, but I haven't added their titles yet - only their URLs. I'm going to do those tomorrow.
I'm also missing the **timestamps**. I'm guessing that work is left for after the episode is released?

The list of cool blogs is also left for tomorrow. I expect to have that, and the topic link titles' done by then.

**Comment by ahl** [comment]
This is wonderful. Thanks so much for getting this started. I'm planning on posting the video tomorrow so will likely take what you have a run with it.

**Comment by scynthiadunlop** [comment]
If anyone wants 50% off the book -- Bryan foreword and all -- they can use the code OXIDE50 on the Manning site.

**Comment by ahl** [comment]
Perfect timing. Hoping to post it in about an hour. Thanks again!! (I don't have Will's info)

**Comment by felix91gr** [comment]
Excellent :grin: 

I found Will's BlueSky! So we have that at least :tada: 

And, regarding this:

> Thanks again!!

It's a pleasure! I've been enjoying and learning a lot from yall's podcast, and since this topic in particular is something I'm really passionate about, I thought I'd give back some love :)
Thanks for letting me add my two cents :heart:

**Comment by felix91gr** [comment]
Alrighty, I think it's done! I can't really add timestamps since... well, the material isn't available just yet XD

Everything else is, as far as I can check, ready for review ^^

@ahl lemme know if anything needs changing; I'll be available during the afternoon.

@scynthiadunlop how does the appendix look? I sorta like it :>

**Pull request merged**
